#!/bin/bash

# Path to the specific image
IMAGE="$HOME/.config/hypr/backgrounds/1314617.jpg"

# Set SWWW transition options
export SWWW_TRANSITION_FPS=144
export SWWW_TRANSITION_STEP=2
export SWWW_TRANSITION_TYPE=random

# Initialize swww if it's not already running
swww query || swww init

# Set the wallpaper
swww img "$IMAGE"
